[tool.poetry]
name = "geoplan2"
version = "0.1.0"
description = ""
authors = ["Artur Duszynski <artur@duszynski.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
